<?php

namespace App\Support;

/**
 * مكتبة إيموجي شاملة (رموز آيفون) مع كلمات مفتاحية للبحث (عربي + إنجليزي).
 * كل عنصر: [الرمز, 'كلمات البحث'].
 */
class Emojis
{
    public static function groups(): array
    {
        return [
            'الوجوه والمشاعر' => [
                ['😀', 'وجه ابتسامة سعيد ضحك grinning smile happy'],
                ['😃', 'وجه سعيد ضحك smile happy'],
                ['😄', 'ضحك سعيد فرح laugh happy'],
                ['😁', 'ابتسامة اسنان grin happy'],
                ['😆', 'ضحك مغمض laughing haha'],
                ['😅', 'ضحك عرق sweat laugh'],
                ['🤣', 'ضحك مقلوب rofl laughing'],
                ['😂', 'ضحك دموع joy tears laugh'],
                ['🙂', 'ابتسامة بسيطة slight smile'],
                ['🙃', 'مقلوب upside down'],
                ['😉', 'غمزة wink'],
                ['😊', 'خجل ابتسامة blush smile happy'],
                ['😇', 'ملاك هالة angel innocent'],
                ['🥰', 'حب قلوب love hearts'],
                ['😍', 'حب عيون قلب heart eyes love'],
                ['🤩', 'نجوم انبهار star struck'],
                ['😘', 'قبلة حب kiss blow'],
                ['😗', 'قبلة kiss'],
                ['😚', 'قبلة خجل kiss'],
                ['😋', 'لذيذ لسان yum tasty'],
                ['😛', 'لسان tongue'],
                ['😜', 'غمزة لسان wink tongue'],
                ['🤪', 'جنون مضحك zany crazy'],
                ['😝', 'لسان مغمض tongue'],
                ['🤑', 'مال دولار money mouth'],
                ['🤗', 'حضن عناق hug'],
                ['🤭', 'يد فم giggle oops'],
                ['🤫', 'صمت هدوء shush quiet'],
                ['🤔', 'تفكير thinking'],
                ['🤐', 'فم مغلق zipper'],
                ['🤨', 'حاجب شك raised eyebrow'],
                ['😐', 'محايد neutral'],
                ['😑', 'بلا تعبير expressionless'],
                ['😶', 'بلا فم no mouth'],
                ['😏', 'ابتسامة ماكرة smirk'],
                ['😒', 'ملل unamused'],
                ['🙄', 'عيون للأعلى roll eyes'],
                ['😬', 'حرج grimace'],
                ['😌', 'ارتياح relieved'],
                ['😔', 'حزن pensive sad'],
                ['😪', 'نعاس sleepy'],
                ['😴', 'نوم sleeping zzz'],
                ['😷', 'كمامة مرض mask sick'],
                ['🤒', 'حرارة مريض sick fever'],
                ['🤕', 'ضمادة اصابة hurt bandage'],
                ['🤢', 'غثيان nausea sick'],
                ['🤮', 'تقيؤ vomit'],
                ['🥵', 'حر حرارة hot'],
                ['🥶', 'برد بارد cold freezing'],
                ['😵', 'دوخة dizzy'],
                ['🤯', 'انفجار عقل mind blown'],
                ['🤠', 'كاوبوي cowboy'],
                ['🥳', 'احتفال حفلة party celebrate'],
                ['😎', 'نظارة كوول cool sunglasses'],
                ['🤓', 'نظارة مثقف nerd'],
                ['🧐', 'عدسة تدقيق monocle'],
                ['😟', 'قلق worried'],
                ['🙁', 'حزن frown sad'],
                ['😮', 'دهشة فم open mouth'],
                ['😲', 'صدمة astonished'],
                ['😳', 'خجل احمرار flushed'],
                ['🥺', 'رجاء عيون pleading'],
                ['😢', 'بكاء دمعة cry sad'],
                ['😭', 'بكاء شديد sobbing cry'],
                ['😱', 'خوف صراخ scream fear'],
                ['😖', 'احباط confounded'],
                ['😞', 'خيبة disappointed'],
                ['😤', 'غضب بخار huffing'],
                ['😡', 'غضب احمر angry rage'],
                ['😠', 'غاضب angry'],
                ['🤬', 'شتم رموز swearing'],
                ['😈', 'شيطان ابتسامة devil'],
                ['👿', 'شيطان غاضب imp devil'],
                ['💀', 'جمجمة موت skull'],
                ['💩', 'كاكا poop'],
                ['🤡', 'مهرج clown'],
                ['👻', 'شبح ghost'],
                ['👽', 'فضائي alien'],
                ['🤖', 'روبوت robot'],
                ['😺', 'قط سعيد cat'],
                ['😻', 'قط حب cat love'],
            ],
            'الإيماءات واليد' => [
                ['👋', 'تلويح مرحبا wave hello'],
                ['🤚', 'يد مرفوعة hand'],
                ['✋', 'يد توقف hand stop'],
                ['🖖', 'تحية سبوك vulcan'],
                ['👌', 'اوكي ok'],
                ['🤏', 'قليل صغير pinch'],
                ['✌️', 'نصر سلام victory peace'],
                ['🤞', 'اصابع حظ fingers crossed'],
                ['🤟', 'حب اشارة love you'],
                ['🤘', 'روك rock'],
                ['🤙', 'اتصل call me'],
                ['👈', 'يسار point left'],
                ['👉', 'يمين point right'],
                ['👆', 'اعلى point up'],
                ['👇', 'اسفل point down'],
                ['☝️', 'اصبع اعلى index up'],
                ['👍', 'اعجاب موافق like thumbs up good'],
                ['👎', 'رفض سيء dislike thumbs down bad'],
                ['✊', 'قبضة fist'],
                ['👊', 'لكمة punch fist'],
                ['👏', 'تصفيق clap'],
                ['🙌', 'رفع يدين raised hands'],
                ['👐', 'يدين مفتوحة open hands'],
                ['🤲', 'دعاء يدين palms'],
                ['🤝', 'مصافحة اتفاق handshake deal'],
                ['🙏', 'دعاء شكر pray thanks please'],
                ['💪', 'عضلة قوة muscle strong'],
                ['👀', 'عيون نظر eyes look'],
                ['👁', 'عين eye'],
                ['👄', 'فم شفاه mouth lips'],
                ['💋', 'قبلة شفاه kiss lips'],
            ],
            'الأشخاص' => [
                ['👶', 'رضيع طفل baby'],
                ['👧', 'بنت طفلة girl'],
                ['👦', 'ولد صبي boy'],
                ['👩', 'امرأة woman'],
                ['👨', 'رجل man'],
                ['👵', 'جدة عجوز old woman'],
                ['👴', 'جد عجوز old man'],
                ['👮', 'شرطي police'],
                ['👷', 'عامل بناء worker'],
                ['💂', 'حارس guard'],
                ['🕵️', 'محقق detective spy'],
                ['🧑‍⚕️', 'طبيب صحة doctor health'],
                ['🧑‍🍳', 'طباخ شيف chef cook'],
                ['🧑‍🎓', 'طالب خريج student graduate'],
                ['🧑‍🏫', 'معلم مدرس teacher'],
                ['🧑‍💻', 'مبرمج حاسوب developer coder'],
                ['🧑‍🔧', 'ميكانيكي فني mechanic'],
                ['🧑‍🌾', 'مزارع farmer'],
                ['🤴', 'امير prince'],
                ['👸', 'اميرة princess'],
                ['🤵', 'عريس بدلة groom tuxedo'],
                ['👰', 'عروس bride'],
                ['🤰', 'حامل pregnant'],
                ['🎅', 'بابا نويل santa'],
                ['🦸', 'بطل خارق superhero'],
                ['🧙', 'ساحر wizard mage'],
                ['💃', 'رقص امرأة dancer'],
                ['🕺', 'رقص رجل dancer'],
                ['🚶', 'مشي walking'],
                ['🏃', 'جري running'],
            ],
            'الحيوانات والطبيعة' => [
                ['🐶', 'كلب dog puppy'],
                ['🐱', 'قط cat'],
                ['🐭', 'فأر mouse'],
                ['🐹', 'هامستر hamster'],
                ['🐰', 'أرنب rabbit bunny'],
                ['🦊', 'ثعلب fox'],
                ['🐻', 'دب bear'],
                ['🐼', 'باندا panda'],
                ['🐨', 'كوالا koala'],
                ['🐯', 'نمر tiger'],
                ['🦁', 'أسد lion'],
                ['🐮', 'بقرة cow'],
                ['🐷', 'خنزير pig'],
                ['🐸', 'ضفدع frog'],
                ['🐵', 'قرد monkey'],
                ['🐔', 'دجاجة chicken'],
                ['🐧', 'بطريق penguin'],
                ['🐦', 'طائر bird'],
                ['🦆', 'بطة duck'],
                ['🦅', 'نسر eagle'],
                ['🦉', 'بومة owl'],
                ['🐺', 'ذئب wolf'],
                ['🐴', 'حصان horse'],
                ['🦄', 'يونيكورن unicorn'],
                ['🐝', 'نحلة bee'],
                ['🐛', 'دودة bug'],
                ['🦋', 'فراشة butterfly'],
                ['🐌', 'حلزون snail'],
                ['🐞', 'دعسوقة ladybug'],
                ['🐢', 'سلحفاة turtle'],
                ['🐍', 'ثعبان snake'],
                ['🐙', 'أخطبوط octopus'],
                ['🦐', 'روبيان جمبري shrimp'],
                ['🦀', 'سلطعون crab'],
                ['🐠', 'سمكة fish'],
                ['🐬', 'دولفين dolphin'],
                ['🐳', 'حوت whale'],
                ['🦈', 'قرش shark'],
                ['🐊', 'تمساح crocodile'],
                ['🐘', 'فيل elephant'],
                ['🐫', 'جمل camel'],
                ['🦒', 'زرافة giraffe'],
                ['🐐', 'ماعز عنزة goat'],
                ['🐑', 'خروف نعجة sheep'],
                ['🐓', 'ديك rooster'],
                ['🦚', 'طاووس peacock'],
                ['🕊', 'حمامة سلام dove peace'],
                ['🐾', 'اثر اقدام paws'],
                ['🌵', 'صبار cactus'],
                ['🌴', 'نخلة palm tree'],
                ['🌲', 'شجرة tree'],
                ['🌱', 'نبتة seedling plant'],
                ['🌿', 'عشب herb'],
                ['☘️', 'برسيم shamrock'],
                ['🍀', 'حظ برسيم clover luck'],
                ['🍃', 'اوراق leaves'],
                ['🍂', 'خريف ورق fall leaves'],
                ['🍁', 'قيقب maple'],
                ['🍄', 'فطر mushroom'],
                ['💐', 'باقة ورد bouquet flowers'],
                ['🌷', 'خزامى تيوليب tulip'],
                ['🌹', 'وردة حمراء rose flower'],
                ['🥀', 'وردة ذابلة wilted rose'],
                ['🌺', 'زهرة كركديه hibiscus flower'],
                ['🌸', 'زهرة كرز blossom flower'],
                ['🌼', 'زهرة daisy flower'],
                ['🌻', 'عباد الشمس sunflower'],
                ['🌾', 'قمح سنابل wheat'],
            ],
            'الطعام والشراب' => [
                ['🍏', 'تفاح اخضر green apple'],
                ['🍎', 'تفاح احمر red apple'],
                ['🍐', 'كمثرى اجاص pear'],
                ['🍊', 'برتقال orange'],
                ['🍋', 'ليمون lemon'],
                ['🍌', 'موز banana'],
                ['🍉', 'بطيخ watermelon'],
                ['🍇', 'عنب grapes'],
                ['🍓', 'فراولة strawberry'],
                ['🫐', 'توت ازرق blueberry'],
                ['🍒', 'كرز cherry'],
                ['🍑', 'خوخ دراق peach'],
                ['🥭', 'مانجو mango'],
                ['🍍', 'اناناس pineapple'],
                ['🥥', 'جوز هند coconut'],
                ['🥝', 'كيوي kiwi'],
                ['🍅', 'طماطم بندورة tomato'],
                ['🥑', 'افوكادو avocado'],
                ['🥦', 'بروكلي broccoli'],
                ['🥒', 'خيار cucumber'],
                ['🌶', 'فلفل حار pepper chili'],
                ['🌽', 'ذرة corn'],
                ['🥕', 'جزر carrot'],
                ['🧄', 'ثوم garlic'],
                ['🧅', 'بصل onion'],
                ['🥔', 'بطاطس potato'],
                ['🥐', 'كرواسون croissant'],
                ['🍞', 'خبز bread'],
                ['🥖', 'خبز فرنسي baguette'],
                ['🧀', 'جبن cheese'],
                ['🥚', 'بيضة egg'],
                ['🍳', 'بيض مقلي fried egg'],
                ['🥞', 'بان كيك pancakes'],
                ['🥓', 'لحم مقدد bacon'],
                ['🥩', 'لحم steak meat'],
                ['🍗', 'دجاج فخذ chicken leg'],
                ['🍖', 'لحمة meat'],
                ['🌭', 'هوت دوج hotdog'],
                ['🍔', 'برجر burger'],
                ['🍟', 'بطاطس مقلية fries'],
                ['🍕', 'بيتزا pizza'],
                ['🥪', 'ساندويتش sandwich'],
                ['🌮', 'تاكو taco'],
                ['🌯', 'شاورما بوريتو wrap burrito'],
                ['🥗', 'سلطة salad'],
                ['🍝', 'مكرونة pasta spaghetti'],
                ['🍜', 'نودلز شوربة ramen noodles'],
                ['🍲', 'طبخة يخنة stew'],
                ['🍛', 'كاري ارز curry rice'],
                ['🍣', 'سوشي sushi'],
                ['🍱', 'علبة طعام bento'],
                ['🍤', 'روبيان مقلي fried shrimp'],
                ['🍚', 'ارز rice'],
                ['🍦', 'ايس كريم ice cream'],
                ['🍨', 'مثلجات ice cream'],
                ['🍧', 'ثلج مبروش shaved ice'],
                ['🥧', 'فطيرة pie'],
                ['🧁', 'كب كيك cupcake'],
                ['🍰', 'كيك قطعة cake slice'],
                ['🎂', 'كيك عيد ميلاد birthday cake'],
                ['🍮', 'كريم كراميل custard'],
                ['🍭', 'مصاصة lollipop'],
                ['🍬', 'حلوى candy'],
                ['🍫', 'شوكولاتة chocolate'],
                ['🍿', 'فشار popcorn'],
                ['🍩', 'دونات donut'],
                ['🍪', 'بسكويت كوكيز cookie'],
                ['🍯', 'عسل honey'],
                ['🥛', 'حليب milk'],
                ['☕', 'قهوة شاي coffee'],
                ['🍵', 'شاي اخضر tea'],
                ['🧃', 'عصير علبة juice box'],
                ['🥤', 'مشروب كوب soda drink'],
                ['🧋', 'شاي فقاعات bubble tea'],
                ['🍺', 'بيرة beer'],
                ['🥂', 'نخب كؤوس cheers'],
                ['🍷', 'نبيذ wine'],
                ['🍾', 'شمبانيا champagne'],
            ],
            'الأنشطة والرياضة' => [
                ['⚽', 'كرة قدم football soccer'],
                ['🏀', 'كرة سلة basketball'],
                ['🏈', 'كرة قدم امريكية football'],
                ['⚾', 'بيسبول baseball'],
                ['🎾', 'تنس tennis'],
                ['🏐', 'كرة طائرة volleyball'],
                ['🏉', 'رجبي rugby'],
                ['🎱', 'بلياردو billiards'],
                ['🏓', 'تنس طاولة ping pong'],
                ['🏸', 'ريشة طائرة badminton'],
                ['🥅', 'مرمى goal'],
                ['⛳', 'جولف golf'],
                ['🏹', 'رماية سهم archery bow'],
                ['🎣', 'صيد سمك fishing'],
                ['🥊', 'ملاكمة boxing'],
                ['🥋', 'كاراتيه karate'],
                ['🛹', 'سكيت skateboard'],
                ['⛸', 'تزلج skating'],
                ['🎿', 'تزلج ثلج ski'],
                ['🏂', 'سنوبورد snowboard'],
                ['🏋️', 'حديد رفع weightlifting gym'],
                ['🤸', 'جمباز gymnastics'],
                ['🧘', 'يوغا تأمل yoga'],
                ['🏄', 'ركوب امواج surfing'],
                ['🏊', 'سباحة swimming'],
                ['🚴', 'دراجة cycling bike'],
                ['🏆', 'كأس جائزة trophy'],
                ['🥇', 'ميدالية ذهب gold medal'],
                ['🥈', 'ميدالية فضة silver medal'],
                ['🥉', 'ميدالية برونز bronze medal'],
                ['🏅', 'ميدالية medal'],
                ['🎯', 'هدف dart target'],
                ['🎳', 'بولينج bowling'],
                ['🎮', 'العاب gaming controller'],
                ['🎲', 'نرد dice'],
                ['🧩', 'احجية puzzle'],
                ['🎨', 'رسم فن art paint'],
                ['🎭', 'مسرح theater'],
                ['🎤', 'مايك غناء microphone'],
                ['🎧', 'سماعات headphones'],
                ['🎸', 'جيتار guitar'],
                ['🎹', 'بيانو piano'],
                ['🥁', 'طبل drum'],
                ['🎺', 'ترومبيت trumpet'],
                ['🎬', 'سينما افلام movie'],
            ],
            'السفر والأماكن' => [
                ['🚗', 'سيارة car'],
                ['🚕', 'تاكسي taxi'],
                ['🚙', 'سيارة دفع suv car'],
                ['🚌', 'باص حافلة bus'],
                ['🏎', 'سيارة سباق race car'],
                ['🚓', 'شرطة سيارة police car'],
                ['🚑', 'اسعاف ambulance'],
                ['🚒', 'اطفاء fire truck'],
                ['🚚', 'شاحنة truck'],
                ['🚛', 'شاحنة كبيرة lorry truck'],
                ['🚜', 'جرار tractor'],
                ['🛴', 'سكوتر scooter'],
                ['🚲', 'دراجة bicycle'],
                ['🏍', 'دراجة نارية motorcycle'],
                ['✈️', 'طائرة plane airplane'],
                ['🚀', 'صاروخ rocket'],
                ['🚁', 'هليكوبتر helicopter'],
                ['⛵', 'قارب شراعي sailboat'],
                ['🚤', 'قارب سريع speedboat'],
                ['🚢', 'سفينة ship'],
                ['⚓', 'مرساة anchor'],
                ['⛽', 'محطة وقود fuel gas'],
                ['🚦', 'اشارة مرور traffic light'],
                ['🗺', 'خريطة map'],
                ['🗽', 'تمثال الحرية statue liberty'],
                ['🏰', 'قلعة castle'],
                ['🎡', 'عجلة دوارة ferris wheel'],
                ['🎢', 'افعوانية roller coaster'],
                ['⛲', 'نافورة fountain'],
                ['🏖', 'شاطئ beach'],
                ['🏝', 'جزيرة island'],
                ['🏜', 'صحراء desert'],
                ['🌋', 'بركان volcano'],
                ['⛰', 'جبل mountain'],
                ['🏕', 'تخييم camping'],
                ['🏠', 'بيت منزل house home'],
                ['🏡', 'منزل حديقة house garden'],
                ['🏢', 'مبنى مكتب office building'],
                ['🏬', 'متجر مول department store'],
                ['🏪', 'بقالة متجر convenience store shop'],
                ['🏫', 'مدرسة school'],
                ['🏥', 'مستشفى hospital'],
                ['🏦', 'بنك bank'],
                ['🏨', 'فندق hotel'],
                ['🏛', 'مبنى حكومي classical building'],
                ['⛪', 'كنيسة church'],
                ['🕌', 'مسجد mosque'],
                ['🕋', 'كعبة kaaba'],
                ['🏭', 'مصنع factory'],
                ['🌆', 'مدينة غروب city'],
                ['🌃', 'مدينة ليل night city'],
                ['🌉', 'جسر bridge'],
                ['🌊', 'موجة بحر wave sea'],
            ],
            'الأشياء والأدوات' => [
                ['⌚', 'ساعة يد watch'],
                ['📱', 'جوال هاتف phone mobile'],
                ['💻', 'لابتوب laptop'],
                ['⌨️', 'كيبورد لوحة مفاتيح keyboard'],
                ['🖥', 'شاشة كمبيوتر desktop computer'],
                ['🖨', 'طابعة printer'],
                ['🖱', 'فأرة mouse'],
                ['💽', 'قرص disk'],
                ['💾', 'حفظ فلوبي save floppy'],
                ['📷', 'كاميرا camera'],
                ['📹', 'كاميرا فيديو video camera'],
                ['🎥', 'كاميرا سينما movie camera'],
                ['📞', 'هاتف telephone'],
                ['☎️', 'هاتف telephone'],
                ['📺', 'تلفزيون tv television'],
                ['📻', 'راديو radio'],
                ['🔋', 'بطارية battery'],
                ['🔌', 'قابس كهرباء plug'],
                ['💡', 'فكرة مصباح idea bulb light'],
                ['🔦', 'كشاف flashlight'],
                ['🕯', 'شمعة candle'],
                ['💸', 'مال طائر money'],
                ['💵', 'دولار نقود dollar cash'],
                ['💴', 'ين yen'],
                ['💶', 'يورو euro'],
                ['💷', 'جنيه pound'],
                ['💰', 'كيس نقود money bag'],
                ['💳', 'بطاقة credit card'],
                ['🧾', 'فاتورة receipt invoice'],
                ['💎', 'ماسة جوهرة diamond gem'],
                ['⚖️', 'ميزان عدل scales balance'],
                ['🧰', 'صندوق ادوات toolbox'],
                ['🔧', 'مفتاح ربط wrench'],
                ['🔨', 'مطرقة hammer'],
                ['🛠', 'ادوات tools'],
                ['🔩', 'مسمار برغي bolt nut'],
                ['⚙️', 'ترس اعداد gear settings'],
                ['🧱', 'طوب bricks'],
                ['🔫', 'مسدس gun'],
                ['🧨', 'مفرقعة firecracker'],
                ['🔪', 'سكين knife'],
                ['🗡', 'سيف dagger sword'],
                ['🛡', 'درع shield'],
                ['🔮', 'كرة سحرية crystal ball'],
                ['🧿', 'عين حسد evil eye'],
                ['💈', 'حلاق barber'],
                ['🔭', 'تلسكوب telescope'],
                ['🔬', 'مجهر microscope'],
                ['💊', 'دواء حبة pill medicine'],
                ['💉', 'حقنة syringe injection'],
                ['🩺', 'سماعة طبيب stethoscope'],
                ['🌡', 'حرارة ميزان thermometer'],
                ['🧹', 'مكنسة broom'],
                ['🧺', 'سلة غسيل basket'],
                ['🧻', 'ورق تواليت toilet paper'],
                ['🚽', 'مرحاض toilet'],
                ['🚿', 'دش shower'],
                ['🛁', 'بانيو bathtub'],
                ['🧼', 'صابون soap'],
                ['🧽', 'اسفنجة sponge'],
                ['🔑', 'مفتاح key'],
                ['🚪', 'باب door'],
                ['🪑', 'كرسي chair'],
                ['🛏', 'سرير bed'],
                ['🧸', 'دبدوب لعبة teddy bear toy'],
                ['🖼', 'اطار صورة frame picture'],
                ['🛍', 'اكياس تسوق shopping bags'],
                ['🛒', 'عربة تسوق shopping cart'],
                ['🎁', 'هدية gift present'],
                ['🎈', 'بالون balloon'],
                ['🎀', 'شريطة ribbon bow'],
                ['🎉', 'احتفال party popper'],
                ['🎊', 'كونفيتي confetti'],
                ['🏮', 'فانوس lantern'],
                ['✉️', 'رسالة ظرف envelope mail'],
                ['📦', 'صندوق طرد box package'],
                ['📫', 'صندوق بريد mailbox'],
                ['📅', 'تقويم calendar'],
                ['📆', 'تقويم calendar date'],
                ['📇', 'بطاقات card index'],
                ['📋', 'حافظة clipboard'],
                ['📁', 'مجلد folder'],
                ['📊', 'رسم بياني bar chart'],
                ['📈', 'ارتفاع رسم chart up'],
                ['📉', 'انخفاض رسم chart down'],
                ['📝', 'ملاحظة كتابة memo note'],
                ['📌', 'دبوس pushpin'],
                ['📍', 'موقع دبوس location pin'],
                ['✂️', 'مقص scissors'],
                ['🖊', 'قلم pen'],
                ['✏️', 'قلم رصاص pencil'],
                ['📏', 'مسطرة ruler'],
                ['🧮', 'معداد حساب abacus'],
                ['🔍', 'بحث عدسة search magnify'],
                ['🔒', 'قفل مغلق lock'],
                ['🔓', 'قفل مفتوح unlock'],
                ['📚', 'كتب books'],
                ['📖', 'كتاب مفتوح open book'],
                ['🔖', 'علامة مرجعية bookmark'],
                ['🏷', 'بطاقة سعر tag label'],
            ],
            'الرموز والقلوب' => [
                ['❤️', 'قلب احمر حب red heart love'],
                ['🧡', 'قلب برتقالي orange heart'],
                ['💛', 'قلب اصفر yellow heart'],
                ['💚', 'قلب اخضر green heart'],
                ['💙', 'قلب ازرق blue heart'],
                ['💜', 'قلب بنفسجي purple heart'],
                ['🖤', 'قلب اسود black heart'],
                ['🤍', 'قلب ابيض white heart'],
                ['🤎', 'قلب بني brown heart'],
                ['💔', 'قلب مكسور broken heart'],
                ['❣️', 'قلب علامة heart exclamation'],
                ['💕', 'قلبين two hearts'],
                ['💞', 'قلوب دوارة revolving hearts'],
                ['💓', 'قلب نابض beating heart'],
                ['💗', 'قلب متزايد growing heart'],
                ['💖', 'قلب لامع sparkling heart'],
                ['💘', 'قلب سهم heart arrow cupid'],
                ['💝', 'قلب هدية heart gift'],
                ['💯', 'مئة كامل hundred perfect'],
                ['✅', 'صح موافق check tick correct'],
                ['❌', 'خطأ غلط cross wrong'],
                ['⭕', 'دائرة circle'],
                ['🛑', 'توقف stop'],
                ['⛔', 'ممنوع no entry'],
                ['🚫', 'محظور prohibited'],
                ['❗', 'تعجب exclamation'],
                ['❓', 'سؤال question'],
                ['⚠️', 'تحذير warning'],
                ['♻️', 'اعادة تدوير recycle'],
                ['⚜️', 'زنبقة fleur de lis'],
                ['🔰', 'مبتدئ beginner'],
                ['⭐', 'نجمة star'],
                ['🌟', 'نجمة لامعة glowing star'],
                ['✨', 'بريق لمعة sparkles'],
                ['⚡', 'برق كهرباء lightning'],
                ['🔥', 'نار حريق fire'],
                ['💥', 'انفجار explosion boom'],
                ['💫', 'دوخة نجمة dizzy'],
                ['💦', 'رذاذ ماء sweat drops'],
                ['💧', 'قطرة ماء droplet'],
                ['🌈', 'قوس قزح rainbow'],
                ['☀️', 'شمس sun'],
                ['⛅', 'غيوم شمس cloud sun'],
                ['☁️', 'غيمة cloud'],
                ['🌧', 'مطر rain'],
                ['❄️', 'ثلج snowflake'],
                ['⛄', 'رجل ثلج snowman'],
                ['🌙', 'هلال قمر moon crescent'],
                ['🌛', 'قمر moon face'],
                ['🌞', 'شمس وجه sun face'],
                ['⚫', 'دائرة سوداء black circle'],
                ['⚪', 'دائرة بيضاء white circle'],
                ['🔴', 'دائرة حمراء red circle'],
                ['🟠', 'دائرة برتقالية orange circle'],
                ['🟡', 'دائرة صفراء yellow circle'],
                ['🟢', 'دائرة خضراء green circle'],
                ['🔵', 'دائرة زرقاء blue circle'],
                ['🟣', 'دائرة بنفسجية purple circle'],
                ['🟤', 'دائرة بنية brown circle'],
                ['🔺', 'مثلث احمر red triangle'],
                ['🔷', 'معين ازرق blue diamond'],
                ['➕', 'زائد جمع plus add'],
                ['➖', 'ناقص طرح minus'],
                ['✖️', 'ضرب multiply'],
                ['➗', 'قسمة divide'],
                ['💲', 'دولار علامة dollar sign'],
                ['🔔', 'جرس تنبيه bell notification'],
                ['🔕', 'جرس صامت mute bell'],
                ['📢', 'مكبر صوت loudspeaker'],
                ['💬', 'محادثة رسالة speech chat'],
                ['💭', 'فكرة بالون thought'],
                ['🕐', 'ساعة وقت clock time'],
                ['♠️', 'بستوني spade'],
                ['♥️', 'كبة قلب heart card'],
                ['♦️', 'ديناري diamond card'],
                ['♣️', 'سباتي club'],
            ],
            'الأعلام' => [
                ['🏁', 'علم سباق checkered flag'],
                ['🚩', 'علم راية flag'],
                ['🏳️', 'علم ابيض white flag'],
                ['🏴', 'علم اسود black flag'],
                ['🇴🇲', 'عمان oman'],
                ['🇸🇦', 'السعودية saudi'],
                ['🇦🇪', 'الامارات uae emirates'],
                ['🇶🇦', 'قطر qatar'],
                ['🇰🇼', 'الكويت kuwait'],
                ['🇧🇭', 'البحرين bahrain'],
                ['🇪🇬', 'مصر egypt'],
                ['🇯🇴', 'الاردن jordan'],
                ['🇱🇧', 'لبنان lebanon'],
                ['🇮🇶', 'العراق iraq'],
                ['🇾🇪', 'اليمن yemen'],
                ['🇵🇸', 'فلسطين palestine'],
                ['🇸🇾', 'سوريا syria'],
                ['🇹🇷', 'تركيا turkey'],
                ['🇺🇸', 'امريكا usa america'],
                ['🇬🇧', 'بريطانيا uk britain'],
                ['🇫🇷', 'فرنسا france'],
                ['🇩🇪', 'المانيا germany'],
                ['🇮🇹', 'ايطاليا italy'],
                ['🇪🇸', 'اسبانيا spain'],
            ],
        ];
    }
}
